"use client";

import Image from "next/image";
import { motion } from "framer-motion";
import { PageIntro, PageShell } from "@/components/SiteChrome";
import { certificates } from "@/lib/portfolio-data";

export default function CertificatesPage() {
  return <PageShell><PageIntro kicker="04 / Certificate vault" title="The long-form evidence." description="Visual previews from Muhammad Ahmed's uploaded certificate portfolio. Open any cover to inspect the original PDF." /><section className="overflow-hidden border-y border-white/10 bg-white/[0.02] py-5"><div className="marquee-track flex gap-3">{[...certificates, ...certificates].map(([title], index) => <span key={`${title}-${index}`} className="whitespace-nowrap rounded-full border border-orange-500/20 px-4 py-2 font-mono text-[11px] text-orange-200/80">✦ {title}</span>)}</div></section><section className="mx-auto grid max-w-7xl gap-4 px-6 py-20 sm:px-10 md:grid-cols-2 lg:grid-cols-3 lg:px-16">{certificates.map(([title, filename, issuer, previewKey], index) => <motion.a whileHover={{ y: -5 }} key={filename} href={`/certificates/${encodeURIComponent(filename)}`} target="_blank" rel="noreferrer" className="glass group overflow-hidden rounded-2xl"><div className="relative aspect-[1.45] overflow-hidden border-b border-white/10 bg-zinc-950"><Image src={`/certificate-previews/certificate-by-name-${previewKey}.jpg`} alt={`${title} certificate preview`} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover object-top opacity-80 transition duration-500 group-hover:scale-105 group-hover:opacity-100" /></div><div className="p-6"><div className="flex items-start justify-between"><span className="font-mono text-xs text-orange-500">{String(index + 1).padStart(2, "0")}</span><span className="rounded-full border border-white/10 px-3 py-1 font-mono text-[10px] uppercase tracking-wider text-zinc-500">PDF</span></div><h2 className="mt-6 text-xl font-semibold leading-tight tracking-[-0.04em] text-zinc-100 group-hover:text-orange-300">{title}</h2><p className="mt-3 text-sm text-zinc-500">{issuer}</p><p className="mt-6 text-sm text-orange-400">Open original certificate ↗</p></div></motion.a>)}</section></PageShell>;
}
